create schema if not exists catalogue;
CREATE TABLE if not exists catalogue.t_product
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_name        VARCHAR(50)                              NOT NULL,
    c_description VARCHAR(1000)                            NOT NULL,
    CONSTRAINT pk_t_product PRIMARY KEY (id)
);