product-shop:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084

server:
  port: 8083


spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/my-shop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-application
            client-secret: ff6SBuvN18lZGQHT2OdAqxJlQJGHNbUq
            scope:
              - openid
              - view_catalogue



logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

