server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - catalogue
    default-schema: catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/my-shop